# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnionTarget.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UnionTarget.proto',
  package='uniseas.fusionTarget.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11UnionTarget.proto\x12\x1duniseas.fusionTarget.protocol\"/\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\xca\x03\n\ncTargProto\x12\x11\n\tdisplayId\x18\x01 \x01(\r\x12\x0c\n\x04mmsi\x18\x02 \x01(\r\x12\x0c\n\x04id_r\x18\x03 \x01(\r\x12\r\n\x05state\x18\x04 \x01(\r\x12\x0f\n\x07quality\x18\x05 \x01(\r\x12\x0e\n\x06period\x18\x06 \x01(\r\x12\x37\n\x06geoPtn\x18\x07 \x01(\x0b\x32\'.uniseas.fusionTarget.protocol.Position\x12\x0e\n\x06\x63ourse\x18\x08 \x01(\x02\x12\r\n\x05speed\x18\t \x01(\x02\x12\x0f\n\x07heading\x18\n \x01(\x02\x12\x0b\n\x03len\x18\x0b \x01(\r\x12\x0b\n\x03wid\x18\x0c \x01(\r\x12\x10\n\x08shiptype\x18\r \x01(\r\x12\x0f\n\x07s_class\x18\x0e \x01(\r\x12\r\n\x05\x66lags\x18\x0f \x01(\r\x12\x0e\n\x06m_mmsi\x18\x10 \x01(\r\x12\x12\n\nvesselName\x18\x11 \x01(\t\x12\x10\n\x08vendorId\x18\x12 \x01(\t\x12\x10\n\x08\x63\x61llSign\x18\x13 \x01(\t\x12\x0b\n\x03imo\x18\x14 \x01(\r\x12\n\n\x02id\x18\x15 \x01(\x04\x12\x0f\n\x07\x66leetId\x18\x16 \x01(\r\x12\x0f\n\x07\x63omment\x18\x17 \x01(\t\x12\x12\n\nrec_course\x18\x18 \x01(\x02\x12\x11\n\trec_speed\x18\x19 \x01(\x02\"\xe1\x01\n\x0bTargetProto\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x36\n\x03pos\x18\x02 \x01(\x0b\x32).uniseas.fusionTarget.protocol.cTargProto\x12\x0c\n\x04sost\x18\x03 \x01(\r\x12\x0e\n\x06lastTm\x18\x04 \x01(\x04\x12\x11\n\tadapterId\x18\x05 \x01(\r\x12=\n\x06status\x18\x06 \x01(\x0e\x32-.uniseas.fusionTarget.protocol.CurStatusProto\x12\x0e\n\x06maxLen\x18\x07 \x01(\r\x12\x0e\n\x06minLen\x18\x08 \x01(\r\"K\n\x0fTargetProtoList\x12\x38\n\x04list\x18\x01 \x03(\x0b\x32*.uniseas.fusionTarget.protocol.TargetProto*A\n\x0e\x43urStatusProto\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\x0b\n\x07\x44\x45LETED\x10\x03\x62\x06proto3'
)

_CURSTATUSPROTO = _descriptor.EnumDescriptor(
  name='CurStatusProto',
  full_name='uniseas.fusionTarget.protocol.CurStatusProto',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEW', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=867,
  serialized_end=932,
)
_sym_db.RegisterEnumDescriptor(_CURSTATUSPROTO)

CurStatusProto = enum_type_wrapper.EnumTypeWrapper(_CURSTATUSPROTO)
UNDEFINED = 0
NEW = 1
UPDATE = 2
DELETED = 3



_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='uniseas.fusionTarget.protocol.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='uniseas.fusionTarget.protocol.Position.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='uniseas.fusionTarget.protocol.Position.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=99,
)


_CTARGPROTO = _descriptor.Descriptor(
  name='cTargProto',
  full_name='uniseas.fusionTarget.protocol.cTargProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='displayId', full_name='uniseas.fusionTarget.protocol.cTargProto.displayId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mmsi', full_name='uniseas.fusionTarget.protocol.cTargProto.mmsi', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_r', full_name='uniseas.fusionTarget.protocol.cTargProto.id_r', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='uniseas.fusionTarget.protocol.cTargProto.state', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quality', full_name='uniseas.fusionTarget.protocol.cTargProto.quality', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='uniseas.fusionTarget.protocol.cTargProto.period', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='geoPtn', full_name='uniseas.fusionTarget.protocol.cTargProto.geoPtn', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='course', full_name='uniseas.fusionTarget.protocol.cTargProto.course', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='uniseas.fusionTarget.protocol.cTargProto.speed', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='uniseas.fusionTarget.protocol.cTargProto.heading', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='len', full_name='uniseas.fusionTarget.protocol.cTargProto.len', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wid', full_name='uniseas.fusionTarget.protocol.cTargProto.wid', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shiptype', full_name='uniseas.fusionTarget.protocol.cTargProto.shiptype', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s_class', full_name='uniseas.fusionTarget.protocol.cTargProto.s_class', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='uniseas.fusionTarget.protocol.cTargProto.flags', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_mmsi', full_name='uniseas.fusionTarget.protocol.cTargProto.m_mmsi', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesselName', full_name='uniseas.fusionTarget.protocol.cTargProto.vesselName', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vendorId', full_name='uniseas.fusionTarget.protocol.cTargProto.vendorId', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callSign', full_name='uniseas.fusionTarget.protocol.cTargProto.callSign', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imo', full_name='uniseas.fusionTarget.protocol.cTargProto.imo', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='uniseas.fusionTarget.protocol.cTargProto.id', index=20,
      number=21, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fleetId', full_name='uniseas.fusionTarget.protocol.cTargProto.fleetId', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='uniseas.fusionTarget.protocol.cTargProto.comment', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rec_course', full_name='uniseas.fusionTarget.protocol.cTargProto.rec_course', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rec_speed', full_name='uniseas.fusionTarget.protocol.cTargProto.rec_speed', index=24,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=560,
)


_TARGETPROTO = _descriptor.Descriptor(
  name='TargetProto',
  full_name='uniseas.fusionTarget.protocol.TargetProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='uniseas.fusionTarget.protocol.TargetProto.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='uniseas.fusionTarget.protocol.TargetProto.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sost', full_name='uniseas.fusionTarget.protocol.TargetProto.sost', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastTm', full_name='uniseas.fusionTarget.protocol.TargetProto.lastTm', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adapterId', full_name='uniseas.fusionTarget.protocol.TargetProto.adapterId', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='uniseas.fusionTarget.protocol.TargetProto.status', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxLen', full_name='uniseas.fusionTarget.protocol.TargetProto.maxLen', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minLen', full_name='uniseas.fusionTarget.protocol.TargetProto.minLen', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=788,
)


_TARGETPROTOLIST = _descriptor.Descriptor(
  name='TargetProtoList',
  full_name='uniseas.fusionTarget.protocol.TargetProtoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='uniseas.fusionTarget.protocol.TargetProtoList.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=790,
  serialized_end=865,
)

_CTARGPROTO.fields_by_name['geoPtn'].message_type = _POSITION
_TARGETPROTO.fields_by_name['pos'].message_type = _CTARGPROTO
_TARGETPROTO.fields_by_name['status'].enum_type = _CURSTATUSPROTO
_TARGETPROTOLIST.fields_by_name['list'].message_type = _TARGETPROTO
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['cTargProto'] = _CTARGPROTO
DESCRIPTOR.message_types_by_name['TargetProto'] = _TARGETPROTO
DESCRIPTOR.message_types_by_name['TargetProtoList'] = _TARGETPROTOLIST
DESCRIPTOR.enum_types_by_name['CurStatusProto'] = _CURSTATUSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'UnionTarget_pb2'
  # @@protoc_insertion_point(class_scope:uniseas.fusionTarget.protocol.Position)
  })
_sym_db.RegisterMessage(Position)

cTargProto = _reflection.GeneratedProtocolMessageType('cTargProto', (_message.Message,), {
  'DESCRIPTOR' : _CTARGPROTO,
  '__module__' : 'UnionTarget_pb2'
  # @@protoc_insertion_point(class_scope:uniseas.fusionTarget.protocol.cTargProto)
  })
_sym_db.RegisterMessage(cTargProto)

TargetProto = _reflection.GeneratedProtocolMessageType('TargetProto', (_message.Message,), {
  'DESCRIPTOR' : _TARGETPROTO,
  '__module__' : 'UnionTarget_pb2'
  # @@protoc_insertion_point(class_scope:uniseas.fusionTarget.protocol.TargetProto)
  })
_sym_db.RegisterMessage(TargetProto)

TargetProtoList = _reflection.GeneratedProtocolMessageType('TargetProtoList', (_message.Message,), {
  'DESCRIPTOR' : _TARGETPROTOLIST,
  '__module__' : 'UnionTarget_pb2'
  # @@protoc_insertion_point(class_scope:uniseas.fusionTarget.protocol.TargetProtoList)
  })
_sym_db.RegisterMessage(TargetProtoList)


# @@protoc_insertion_point(module_scope)
